goodhabits/models.py
from datetime import datetime
from goodhabits import db, login_manager
from flask_login import UserMixin
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app

@login_manager.user_loader
def load_user(user_id):
	return User.query.get(int(user_id))

class User(db.Model,UserMixin):
	__tablename__ = 'users'
	id = db.Column(db.Integer, primary_key=True)
	username = db.Column(db.String(20),unique=True, nullable=False)
	email = db.Column(db.String(120), unique=True, nullable=False)
	image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
	password = db.Column(db.String(60), nullable=False)
	habits = db.relationship('Habit', backref='owner', lazy=True)

	def get_reset_token(self, exprires_sec=1800):
		s = Serializer(current_app.config['SECRET_KEY'], exprires_sec)
		return s.dumps({'user_id': self.id}).decode('utf-8')

	@staticmethod
	def verify_reset_token(token):
		s = Serializer(current_app.config['SECRET_KEY'])
		try:
			user_id = s.loads(token)['user_id']
		except:
			return None
		return User.query.get(user_id)

	def __repr__(self):
		return f"User('{self.username}','{self.email}','{self.image_file}')"


class Habit(db.Model):
	__tablename__ = 'habits'
	id = db.Column(db.Integer, primary_key=True)
	name = db.Column(db.String(100), nullable=False)
	date_created = db.Column(db.DateTime, nullable= False, default=datetime.utcnow)
	user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
	events = db.relationship('HabitEvent', backref='habit', lazy=True)


	def __repr__(self):
		return f"Habit('{self.name}','{self.date_created}','{self.user_id}')"

class HabitEvent(db.Model):
	__tablename__ = 'habitevent'
	id = db.Column(db.Integer, primary_key=True)
	date_occurred = db.Column(db.Date, nullable= False)
	age = db.Column(db.Integer)
	habit_id = db.Column(db.Integer, db.ForeignKey('habits.id'), nullable=False)

	def __repr__(self):
		return f"HabitEvent('{self.date_occurred}','{self.habit_id}')"

goodhabits/habits/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class HabitForm(FlaskForm):
	name = StringField('Name', validators=[DataRequired()])
	submit = SubmitField('Create habit')

goodhabits/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class HabitForm(FlaskForm):
	name = StringField('Name', validators=[DataRequired()])
	submit = SubmitField('Create habit')

goodhabits/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
from goodhabits.models import User

class RegistrationForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired(),Length(min=2,max=20)])
	email = StringField('Email', validators=[DataRequired(),Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password', validators=[DataRequired(),EqualTo('password')])

	submit = SubmitField('Sign Up')

	def validate_username(self, username):
		user = User.query.filter_by(username=username.data).first()
		if user:
			raise ValidationError('That username is taken, please choose a different one!')

	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user:
			raise ValidationError('That email is taken, please choose a different one!')

class LoginForm(FlaskForm):
	email = StringField('Email', validators=[DataRequired(),Email()])
	password = PasswordField('Password', validators=[DataRequired()])
	remember = BooleanField('Remember Me')

	submit = SubmitField('Log In')


class UpdateAccountForm(FlaskForm):
	username = StringField('Username', validators=[DataRequired(),Length(min=2,max=20)])
	email = StringField('Email', validators=[DataRequired(),Email()])
	picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg','png'])])
	submit = SubmitField('Update')

	def validate_username(self, username):
		if username.data != current_user.username:
			user = User.query.filter_by(username=username.data).first()
			if user:
				raise ValidationError('That username is taken, please choose a different one!')

	def validate_email(self, email):
		if email.data != current_user.email:
			user = User.query.filter_by(email=email.data).first()
			if user:
				raise ValidationError('That email is taken, please choose a different one!')


class RequestResetForm(FlaskForm):
	email = StringField('Email', validators=[DataRequired(),Email()])
	submit = SubmitField('Request Password Reset')


	def validate_email(self, email):
		user = User.query.filter_by(email=email.data).first()
		if user is None:
			raise ValidationError('There is no account with that email, you must register first!')

class ResetPasswordForm(FlaskForm):
	password = PasswordField('Password', validators=[DataRequired()])
	confirm_password = PasswordField('Confirm Password', validators=[DataRequired(),EqualTo('password')])

	submit = SubmitField('Reset Password')

goodhabits/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from goodhabits.config import Config
# from flask_mail import Mail
from flask_migrate import Migrate

db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'


# mail = Mail()

migrate = Migrate()

def create_app(config_class=Config):
	app = Flask(__name__)

	app.config.from_object(Config)	

	db.init_app(app)
	bcrypt.init_app(app)
	login_manager.init_app(app)
	# mail.init_app(app)
	migrate.init_app(app, db)

	from goodhabits.users.routes import users
	app.register_blueprint(users)

	from goodhabits.habits.routes import habits
	app.register_blueprint(habits)

	from goodhabits.main.routes import main
	app.register_blueprint(main)

	from goodhabits.errors.handlers import errors
	app.register_blueprint(errors)

	return app

goodhabits/habits/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint,jsonify)
from flask_login import current_user, login_required
from goodhabits import db
from goodhabits.models import HabitEvent, Habit
from goodhabits.habits.forms import HabitForm
from datetime import datetime, timedelta

habits = Blueprint('habits', __name__)

@habits.route('/habit_event/new', methods=["POST"])
# @login_required
def new_habit_event():
	request_data= request.get_json()
	day = datetime.strptime(request_data['date'],'%Y-%m-%d')
	previous_day = day - timedelta(1)

	existing_event = HabitEvent.query.filter_by(habit_id=request_data['habit'],date_occurred=day).first()
	previous_day_event = HabitEvent.query.filter_by(habit_id=request_data['habit'],date_occurred=previous_day).first()
	
	if existing_event:
		db.session.delete(existing_event)
		db.session.commit()
		return jsonify(age=0), 201
	else:
		habit = Habit.query.filter_by(id=request_data['habit']).first_or_404()
		age = previous_day_event.age + 1 if (previous_day_event and previous_day_event.age) else 1
		habit_event = HabitEvent(habit=habit, date_occurred=day, age=age)
		db.session.add(habit_event)
		db.session.commit()
		return jsonify(age=age), 201

@habits.route('/habit/delete', methods=['POST'])
def deleteHabit():
	request_data = request.get_json()

	habit = Habit.query.filter_by(id=request_data['habit_id']).first_or_404()
	habit_event = HabitEvent.query.filter_by(habit=habit).all()
	for h_e in habit_event:
		db.session.delete(h_e)
	db.session.delete(habit)
	db.session.commit()
	return 'Done', 201

goodhabits/main/routes.py
from flask import render_template, request, Blueprint, flash,redirect, url_for, Flask, send_from_directory
from goodhabits.models import Habit
from goodhabits.habits.forms import HabitForm
from flask_login import current_user, login_required
from goodhabits import db
import itertools
from datetime import datetime, date, timedelta

main = Blueprint('main', __name__)


@main.route("/", methods=["GET","POST"])
@main.route("/home", methods=["GET","POST"])
def home():

	if (current_user.is_authenticated is False):
		return render_template('landing.html')

	month = request.args.get('month')
	month = month if month else datetime.today().strftime("%Y-%m")
	current_month = datetime.strptime(month, '%Y-%m')

	next_month = (current_month + timedelta(days=45)).replace(day=1)
	prev_month = (current_month - timedelta(days=15)).replace(day=1)
	months={'prev_month':prev_month,'current_month':current_month,'next_month':next_month}

	habits = Habit.query.filter_by(owner=current_user).all()

	calendar_query =\
"""SELECT 
dd::DATE as day_number,
h.id as habit,
h_e.age as habit_events
FROM generate_series
        ( (date_trunc('month', date '{month}') - INTERVAL '2 day')::timestamp 
        , (date_trunc('month', date '{month}') + INTERVAL '31 day')::timestamp
        , '1 day'::interval) dd
JOIN habits h ON h.user_id = {current_user_id}
LEFT JOIN habitevent h_E ON h_e.habit_id = h.id AND h_e.date_occurred::DATE = dd::DATE
ORDER BY dd::DATE ASC, habit ASC;"""\
.format(current_user_id=current_user.id,month=month+'-01');
	calendar = db.session.execute(calendar_query).fetchall()

	calendar = [{'date':key,'events':list(group)} for key,group in itertools.groupby(calendar, key=lambda x:x[0])]
	form = HabitForm()
	if form.validate_on_submit():
		habit = Habit(name=form.name.data, owner=current_user)
		db.session.add(habit)
		db.session.commit()
		flash('Your habit has been created!', 'success')
		return redirect(url_for('main.home'))

	return render_template('home.html', title='Home', form=form, habits=habits, calendar=calendar, today=date.today(),months=months)



@main.route("/landing")
def landing():
	return render_template('landing.html')


@main.route('/robots.txt')
@main.route('/sitemap.xml')
def static_from_root():
    return send_from_directory('static', request.path[1:])

goodhabits/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from goodhabits import db, bcrypt
from goodhabits.models import User, Habit#, HabitEvent
from goodhabits.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from goodhabits.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=["GET","POST"])
def register():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RegistrationForm()
	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email = form.email.data , password = hashed_password)
		db.session.add(user)
		db.session.commit()
		flash(f'Your account has been created, you are now able to log in', "success") 
		return redirect(url_for('users.login'))

	return render_template('register.html', title='Register', form = form)


@users.route("/login", methods=["GET", "POST"])
def login():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email= form.email.data).first()
		if user and bcrypt.check_password_hash(user.password, form.password.data):
			login_user(user, remember=form.remember.data)
			next_page = request.args.get('next')
			return redirect(next_page) if next_page else redirect(url_for('main.home'))
		else:
			flash('Login unsuccessful. Please check email and password!', 'danger')
	return render_template('login.html', title='Login', form = form)

@users.route('/logout')
def logout():
	logout_user()
	return redirect(url_for('main.home'))

@users.route('/account', methods=["GET", "POST"])
@login_required
def account():
	form = UpdateAccountForm()
	if form.validate_on_submit():
		if form.picture.data:
			picture_file = save_picture(form.picture.data)
			current_user.image_file = picture_file
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('Your account has been updated!','success')
		return redirect(url_for('users.account'))
	elif request.method =="GET":
		form.username.data = current_user.username
		form.email.data	= current_user.email
	image_file = url_for('static', filename='profile_pics/'+current_user.image_file)
	return render_template('account.html', title='Account', image_file=image_file, form = form)

@users.route('/reset_password', methods=["GET", "POST"])
def reset_request():
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	form = RequestResetForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		send_reset_email(user)
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=["GET", "POST"])
def reset_token(token):
	if current_user.is_authenticated:
		return redirect(url_for('main.home'))
	user = User.verify_reset_token(token)
	if user is None:
		flash('That is an invalid or expired token', 'warning')
		return redirect(url_for('users.reset_request'))
	form = ResetPasswordForm()

	if form.validate_on_submit():
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user.password= hashed_password
		db.session.commit()
		flash(f'Your password has been updated.', "success") 
		return redirect(url_for('users.login'))
	return render_template('reset_token.html', title='Reset Password', form=form)

goodhabits/templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="card auth">
	<form class='auth_form'action="" method="POST" enctype="multipart/form-data">
		{{	form.hidden_tag() }}
		<fieldset class="auth_form">
			<legend class="border-bottom mb-4">Account Info</legend>
			<div class="form-group">
				{{form.username.label(class="form-control-label")}}
				{% if form.username.errors %}
					{{form.username(class="form-control-input")}}
				<div class="invalid-feedback">
					{% for error in form.username.errors %}
						<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %}
				{{form.username(class="form-control-input")}}
				{% endif %}
			</div>
			<div class="form-group">
				{{form.email.label(class="form-control-label")}}
				{% if form.email.errors %}
					{{form.email(class="form-control-input")}}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
						<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %}
				{{form.email(class="form-control-input")}}
				{% endif %}
			</div>
			<img class="img-rounded-circle form-group" src="{{image_file}}">
			<div class="form-group">
				{{ form.picture.label(class="form-control-label") }}
				{{ form.picture(class="form-control-file") }}
				{% if form.picture.errors %}
					{% for error in form.picture.errors %}
						<span class="text-danger">{{error}}</span></br>
					{% endfor %}
				{% endif %}
			</div>
		</fieldset>
		<div class="form-group">
			{{form.submit(class="submit-button black-button")}}
		</div>
	</form>
</div>
{% endblock content%}
{% block scripts %}
	<script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

goodhabits/templates/home.html
{% extends "layout.html" %}

{% block content %}

<div class="card home">

	{% if calendar == [] %}
	<div class="empty_state">
		<h2>You don't have any active habits</h2>
		<p>Get started with your first habit</p>
		<button id="new_habit" class="black-button">Add habit</button>
	</div>
	{% else %}

	<div class="calendar">
		<div class="calendar_header">
			<a href="/home?month={{months.prev_month.year}}-{{months.prev_month.month}}">
				<div id="previous_month"><span class="month_arrow">&#9664;</span>Prev<span class='full_month'>ious month</span></div>
			</a>
			<div class="month_name">{{months.current_month.strftime("%B")}}</div>
			<a href="/home?month={{months.next_month.year}}-{{months.next_month.month}}">
				<div id="next_month">Next<span class='full_month'>&nbsp;month</span><span class="month_arrow">&#9654;</span></div>
			</a>
		</div>
		<div class="calendar_container">
 			{% for day in calendar %}
					<div class="day_group">
					{% if day.date.month != months.current_month.month %}
						<div class="date greyed">{{day.date.day}}</div>
					{% elif day.date == today %}
						<div class="date today">{{day.date.day}}</div>
					{% else %}
						<div class="date">{{day.date.day}}</div>
					{% endif %}
		 			{% for d,habit,event in day.events %}
		 				{% if day.date == today %}
							{% if event == None %}
			 					<div onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today" data_id="{{habit}}"></div>
			 				{% elif event > 20 %}
			 					<div  onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today level6" data_id="{{habit}}"></div>
							{% elif event>11 %}
			 					<div  onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today level5" data_id="{{habit}}"></div>
							{% elif event>6 %}
			 					<div  onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today level4" data_id="{{habit}}"></div>
							{% elif event>3 %}
			 					<div  onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today level3" data_id="{{habit}}"></div>
							{% elif event>1 %}
			 					<div  onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today level2" data_id="{{habit}}"></div>
			 				{% else %}
			 					<div  onclick="toggleCompletion(caller=this,date='{{day.date}}',habit={{habit}})" class="row today level1" data_id="{{habit}}"></div>
			 				{% endif %}
		 				{% else %}
							{% if event == None %}
			 					<div class="row" data_id="{{habit}}"></div>
			 				{% elif event > 20 %}
			 					<div class="row level6" data_id="{{habit}}"></div>
							{% elif event>11 %}
			 					<div class="row level5" data_id="{{habit}}"></div>
							{% elif event>6 %}
			 					<div class="row level4" data_id="{{habit}}"></div>
							{% elif event>3 %}
			 					<div class="row level3" data_id="{{habit}}"></div>
							{% elif event>1 %}
			 					<div class="row level2" data_id="{{habit}}"></div>
			 				{% else %}
			 					<div class="row level1" data_id="{{habit}}"></div>
			 				{% endif %}
		 				{% endif %}
					{% endfor %}
				</div>
			{% endfor %}
 		</div>
	</div>
	<div class="habits">
		<div class="habit_header">
			<h2>Habits</h2>
			<button id="new_habit">+ Add habit</button>
		</div>
		{% for i in range(7) %}
		{% if i<2 %}
		<div class="habit_list">
		{% elif i<5 %}
		<div class="habit_list tablet">
		{% else %}
		<div class="habit_list phone">
		{% endif %}
			{% for habit in habits%}
			<div class="habit" data_id="{{habit.id}}" onmouseover="this.getElementsByTagName('span')[0].style.display='flex';" onmouseout="this.getElementsByTagName('span')[0].style.display='none';">
				{{ habit.name }}
				<span class="delete_habit">
					<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
					<rect x="6" y="10" width="10" height="2" fill="#BBBBBB"/>
					<rect x="0.5" y="0.5" width="21" height="21" rx="1.5" stroke="#BBBBBB"/>
					</svg>
				</span>
			</div>
			{% endfor %}
		</div>
		{% endfor %}
	</div>
</div>
	{% endif %}

<div id="modal">
	<div class="modal_bg"></div>
	<div class="card" id="create_habit_modal">
		<form action="" method="POST">
			{{	form.hidden_tag() }}
			<fieldset>
				<legend>New habit</legend>
				<div>
					{% if form.name.errors %}
						{{form.name(class="form-control-input")}}
					<div class="invalid-feedback">
						{% for error in form.name.errors %}
							<span>{{error}}</span>
						{% endfor %}
					</div>
					{% else %}
					{{form.name(class="form-control-input")}}
					{% endif %}
				</div>
				<div>
					{{form.submit(class='black-button')}}
				</div>
			</fieldset>
		</form>		
	</div>
	<div class="card" id="delete_habit_modal">
		<h2>Are you sure?</h2>
		<div>You are about to delete this habit. All previous date will be lost.</div>
			<div>
				<button class="black-button" id="confirm_delete" >Delete habit</button>
				<button id="cancel_delete">Cancel</button>
			</div>
	</div>


</div>
	
{% endblock content %}
{% block scripts %}
	<script src="{{ url_for('static', filename='main.js') }}"></script>
	<script src="{{ url_for('static', filename='home.js') }}"></script>
{% endblock %}

goodhabits/templates/landing.html
{% extends "layout.html" %}
{% block content %}
<div class="landing">
	
  	<img src="{{ url_for('static', filename='landing.png') }}">
	<div class="">
		
		<h1>Don't break the chain</h1>

	<div class="tagline">Track your daily habits with this free habit tracker and keep up the good work!</div>
		<a href="/register">
	<div class="cta">Sign up</div>
		</a>
	</div>
</div>

<div class="quote_section">
	<div class="quote_box">
		<div class="quote">
			If you want better results, then forget about setting goals. Focus on your system instead.
		</div>
		<div class="author">— James  Clear —<br> Author of “atomic habits”</div>
	</div>
</div>

<div class="steps">
	<div class="step">
		<div class="step_numb_holder"><div class="step_number step1">1
		</div></div>
		<div class="step_desc">
			<h3>Add your first habit</h3>
			<p>You have daily habits you want to track and want to follow your progress online. Maybe you just started distance learning and want to keep good habits. </p>
		</div>
	</div>
	<div class="step">
		<div class="step_desc">
			<h3>Check your progress daily</h3>
			<p>Come back everyday once you’ve completed your habit and check it off. Repeat this enough times and you’ve built a routine!</p>
		</div>
		<div class="step_numb_holder"><div class="step_number step2">2</div></div>
	</div>
	<div class="step">
		<div class="step_numb_holder"><div class="step_number step3">3</div></div>
		<div class="step_desc">
			<h3>Get (gentle) reminders when you miss a day</h3>
			<span>— Coming soon —</span>
			<p>You have daily habits you want to track and want to follow your progress online. Maybe you just started distance learning and want to keep good habits. </p>
		</div>
	</div>
</div>

<div class="divider"></div>

<div class="why">
	<div class="why_header">	
		<h2>Why use an online habit tracker?</h2>
	</div>
	<p>You may have tried in the past to track your habits. You made a list of the best habits to track, found a printout calendar and hung it up on your fridge. If you were like me, you did it for a couple weeks and then the hassle of looking for a pen each morning was too much. One day you missed filling the calendar. Then you missed a couple of days, and before you knew it you weren’t tracking it at all anymore. And then you lost the habit. </p>
	<p>You can break down a habit into a feedback loop with four steps: <strong>cue, craving, response &amp; reward</strong>. The trick to stay commited is to have the cue not come from you but from an external source. If the cue doesn’t come from you, you don’t have to spend the extra cognitive energy reminding yourself to check your list of habits - it reminds you of what is left to do.</p>
	<p>Remember habit tracking is not the same as goal setting. Continuous habits over years act like compound interest on your skills and abilities, much more than some ambitious but sparse objectives.</p>


</div>

{% endblock content%}
{% block scripts %}
	<script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}

goodhabits/templates/layout.html
<!DOCTYPE html>
<html>
<head>

	<!-- Analytics -->
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-164031381-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-164031381-1');
	</script>
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link href="https://fonts.googleapis.com/css2?family=Encode+Sans:wght@100;200;300;400;500;600;700;800;900&family=Enriqueta:wght@400&display=swap" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
	{% block scripts %}
	{% endblock %}
	<title>Trackhabits - free online habit tracker to improve your daily habits</title>
	<meta name="description" content="Track your habits online. Good actions only become good habits if you do them regularly. Create your routine by logging your progress every day!">
</head>
<body>
	<header class="site-header">
	  <nav class="navbar">
	      <a class="logo" href="/">
	      	<img src="{{ url_for('static', filename='logo.png') }}">
	      </a>
	      <div id="hamburger">
	      	<ul>
	      		<li></li>
	      		<li></li>
	      		<li></li>
	      	</ul>
	      </div>
	        <div class="navbar-nav">
	        	{% if current_user.is_authenticated %}
	        	  <a href="{{url_for('users.account')}}">Account</a>
	        	  <a href="{{url_for('users.logout')}}">Logout</a>
	        	{% else %}
		          <a href="{{url_for('users.login')}}">Login</a>
		          <a class="sign_up" href="{{url_for('users.register')}}">Sign Up</a>
	          {% endif %}
	        </div>
	      </div>

	  </nav>
	</header>

	<main role="main" class="container">  
	      {% block content %}{% endblock %}
	</main>

	

	<footer>
		<span>
			Made with 🖤 during the Coronavirus crisis
		</span>
	</footer>
</body>
</html>

goodhabits/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="card auth">
	<form action="" method="POST" class="auth_form">
		{{	form.hidden_tag() }}
		<fieldset class="auth_form">
			<legend>Log In</legend>
			<div class="form-group">
				{{form.email.label(class="form-control-label")}}
				{% if form.email.errors %}
					{{form.email(class="form-control-input")}}
				<div class="invalid-feedback">
					{% for error in form.email.errors %}
						<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %}
				{{form.email(class="form-control-input")}}
				{% endif %}
			</div>
			<div class="form-group">
				{{form.password.label(class="form-control-label")}}
				{% if form.password.errors %}
					{{form.password(class="form-control-input")}}
				<div class="invalid-feedback">
					{% for error in form.password.errors %}
						<span>{{error}}</span>
					{% endfor %}
				</div>
				{% else %}
				{{form.password(class="form-control-input")}}
				{% endif %}
			</div>
			<div class=" remember_me">
				{{ form.remember() }}
				{{ form.remember.label() }}

			</div>
		</fieldset>
		<div class="form-group">
			{{form.submit(class="submit-button black-button")}}
			<a class='extra_links' href="{{url_for('users.reset_request')}}">Forgot Password?</a>
		</div>
	</form>
</div>
<div class="extra_links">
		Need an account? <a href="{{url_for('users.register')}}" class="ml-2">Sign Up Now</a>
</div>
{% endblock content%}
{% block scripts %}
	<script src="{{ url_for('static', filename='main.js') }}"></script>
{% endblock %}